version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: ai-docs-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: ai_docs_assistant
    networks:
      - ai-docs-network

  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-docs-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - DATABASE_NAME=ai_docs_assistant
    depends_on:
      - mongodb
    networks:
      - ai-docs-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-docs-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - ai-docs-network

  # Nginx (opzionale - per produzione)
  nginx:
    image: nginx:alpine
    container_name: ai-docs-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - ai-docs-network
    profiles:
      - production

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  ai-docs-network:
    driver: bridge